# backend/services/tts_service.py
import os
import numpy as np
import soundfile as sf
from backend.core.config import settings

_pipeline = None

def get_pipeline():
    """Lazily load the Kokoro pipeline."""
    global _pipeline
    if _pipeline is None:
        import torch
        # Optimize CPU inference threads to reduce scheduling overhead
        torch.set_num_threads(4)
        from kokoro import KPipeline
        print("Initializing Kokoro KPipeline for TTS (threads=4)...")
        _pipeline = KPipeline(lang_code='a')
    return _pipeline

def generate_tts_for_question(session_id: str, question_id: str, text: str, voice: str = "af_sarah") -> str:
    """
    Generate speech audio (.wav) for the question text.
    Caches the audio file to avoid synthesizing the same question multiple times.
    Returns the absolute file path to the generated WAV file.
    """
    tts_dir = os.path.join(settings.BASE_DATA_DIR, "tts_audio")
    os.makedirs(tts_dir, exist_ok=True)
    
    # Generate unique filename for caching
    safe_filename = f"question_{session_id}_{question_id}.wav"
    output_path = os.path.join(tts_dir, safe_filename).replace("\\", "/")
    
    if os.path.exists(output_path):
        print(f"Using cached TTS audio: {output_path}")
        return output_path
        
    try:
        pipeline = get_pipeline()
        generator = pipeline(text, voice=voice, speed=1.0)
        
        audio_segments = []
        for gs, ps, audio in generator:
            if audio is not None and len(audio) > 0:
                audio_segments.append(audio)
                
        if not audio_segments:
            raise ValueError("No audio was generated by Kokoro.")
            
        full_audio = np.concatenate(audio_segments)
        
        # Save audio file (Kokoro runs at 24000Hz samplerate)
        sf.write(output_path, full_audio, 24000)
        print(f"Successfully generated TTS audio: {output_path}")
        return output_path
        
    except Exception as e:
        print(f"Error generating TTS audio: {e}")
        # Return empty or fallback if failed
        return ""
